# Generated by Django 4.1.5 on 2023-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=256)),
                ('pages', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('front_cover', models.ImageField(upload_to='')),
                ('back_cover', models.ImageField(upload_to='')),
                ('spine', models.ImageField(upload_to='')),
                ('properties', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
